### ISSUE TITLE
Name in details message is 'undefined'

### ISSUE THREAD

**Issue by muhamed-didovic** [LucasRodrigues/health-check-rabbitmq#1]
Thanks for great package.

I am using your health-check-system package for mongo and rabbitmq.
I have an issue with rabbitmq part this is my code:

`var configuration = {
  "mongodb": [
    {
      url: 'mongodb://localhost/audit'
    }
  ],
  "rabbitMq": [
    {
      host: 'localhost',
      port: 5672
    },
    {
      host: 'localhost',
      port: 4369
    },
    {
      host: 'localhost',
      port: 35197
    },
    {
      host: 'wronghost',
      port: 5672
    },
    {
      host: 'wronghost',
      port: 6379
    }
  ]
};

healthCheckSystem.do(configuration)
  .then(function (result) {
    console.log('1111111');
    log.info(result);
  })
  .catch(function (error) {
    console.log('22222');
    log.error(error);
  });`

and the output is:

`success: {
      "total": 6,
      "details": [
        {
          "name": "mongodb://localhost/audit",
          "health": true,
          "message": ""
        },
        {
          "name": "undefined",
          "health": true,
          "message": ""
        },
        {
          "name": "undefined",
          "health": true,
          "message": ""
        },
        {
          "name": "undefined",
          "health": true,
          "message": ""
        },
        {
          "name": "undefined",
          "health": true,
          "message": ""
        },
        {
          "name": "undefined",
          "health": true,
          "message": ""
        }
      ]
    }
    --
    error: {
      "total": 0,
      "details": []
    }`

As you can see 'name' property is 'undefined', also if you can write some tests for packages, that would be great.

**Comment by muhamed-didovic** [comment]
small update, we need url inside configuration in order to work properly

**Comment by LucasRodrigues** [comment]
@muhamed-didovic thanks Muhamed for report!! I Fix this example, i need to review all! Thanks a lot!

**Comment by muhamed-didovic** [comment]
Hi Lucas, thanks for feedback. Also I think your packages are great and simple.

As said before adding tests will provide quality and ensurance. 
Regarding databases we check only if we are able to connect them? 
I would go step futher and add small select like "select 1+1" just to ensure.

For rabbit, they have url '/api/aliveness-test/vhost' for alivness, you can check more:http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v2_2_0/priv/www-api/help.html
